name: Bump casks

on:
  workflow_dispatch:
    inputs:
      casks:
        description: List of casks to livecheck and bump if outdated
        required: false
  schedule:
    # Every day at 3am
    - cron: "0 3 * * *"

permissions:
  contents: write
  pull-requests: write

env:
  CASKS: >
    jck112/cask/balenaetcher
    jck112/cask/ffmpeg
  HOMEBREW_DEVELOPER: "1"
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: "1"
  HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
  HOMEBREW_NO_AUTO_UPDATE: "1"

jobs:
  autobump:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:latest
    steps:
      - name: Fix filesystem permissions
        run: sudo chown -Rv "$(whoami)" "$HOME" "$GITHUB_WORKSPACE"

      - name: Configure git
        run: |
          git config --global url."https://api:${HOMEBREW_GITHUB_API_TOKEN}@github.com/".insteadOf "https://github.com/"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"

      - name: Checkout repository
        run: |
          git init -b "$GITHUB_REF_NAME"
          git remote add origin "https://github.com/${GITHUB_REPOSITORY}"
          git fetch origin "$GITHUB_SHA" '+refs/heads/*:refs/remotes/origin/*'
          git remote set-head origin --auto
          git checkout --force -B "$GITHUB_REF_NAME" FETCH_HEAD

      - name: Set environment variables
        run: |
          echo "HOMEBREW_REPOSITORY=$(brew --repo)" | sudo tee -a $GITHUB_ENV
          echo "HOMEBREW_TAP_REPOSITORY=$(brew --repo $GITHUB_REPOSITORY)" | sudo tee -a $GITHUB_ENV

      - name: Setup tap
        run: |
          mkdir -vp "${HOMEBREW_TAP_REPOSITORY%/*}"
          ln -vs "$GITHUB_WORKSPACE" "$HOMEBREW_TAP_REPOSITORY"

      - name: Patch 'brew bump'
        run: |
          git -C "$HOMEBREW_REPOSITORY" apply \
          "$HOMEBREW_TAP_REPOSITORY/.github/workflows/brew-bump.patch"

      - name: Bump casks
        run: brew bump --open-pr --no-fork --automerge ${{ github.event.inputs.casks || env.CASKS }}
