name: Bump casks

on:
  workflow_dispatch:
  schedule:
    # Every day at 3am
    - cron: "0 3 * * *"

permissions:
  contents: write
  pull-requests: write

env:
  CASKS: >
    jck112/cask/balenaetcher
    jck112/cask/ffmpeg
  HOMEBREW_DEVELOPER: "1"
  HOMEBREW_FORCE_HOMEBREW_ON_LINUX: "1"
  HOMEBREW_GITHUB_API_TOKEN: ${{ github.token }}
  HOMEBREW_NO_AUTO_UPDATE: "1"

jobs:
  autobump:
    runs-on: ubuntu-22.04
    container:
      image: ghcr.io/homebrew/ubuntu22.04:latest
      options: --pull always --user root
    steps:
      - uses: tidylabs/action-git-config-user@v1
      - uses: actions/checkout@v4

      - name: Set environment variables
        run: |
          echo "HOMEBREW_REPOSITORY=$(brew --repo)" | sudo tee -a $GITHUB_ENV
          echo "HOMEBREW_TAP_REPOSITORY=$(brew --repo $GITHUB_REPOSITORY)" | sudo tee -a $GITHUB_ENV

      - name: Setup tap
        run: |
          mkdir -vp "${HOMEBREW_TAP_REPOSITORY%/*}"
          ln -vs "$GITHUB_WORKSPACE" "$HOMEBREW_TAP_REPOSITORY"

      - name: Bump casks
        run: brew bump --open-pr --no-fork ${{ github.event.inputs.casks || env.CASKS }}
